failover.err line 4: No failover support.
